version: 1.0

image: Ubuntu1804

branches:
  only:
    - main

build:
  mode: script

init:
  - echo "Installing NVM..."
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  - export NVM_DIR="$HOME/.nvm"
  - source "$NVM_DIR/nvm.sh"
  - echo "Installing Node.js..."
  - nvm install 16
  - nvm use 16

install:
  - echo "Installing dependencies..."
  - cd client  
  - npm install

before_build:
  - cd client  
  - rm -rf dist/

build_script:
  - cd client  
  - echo "Building the project..."
  - npm run build

deploy_script:
  - cd client  
  - echo "Deploying to GitHub Pages..."
  - cp -r dist/* .  
  - git config user.name "AppVeyor"  
  - git config user.email "ci@appveyor.com"  
  - git config credential.helper "store --file=$HOME/.git-credentials"  
  - echo "https
