version: 1.0.1
image: Ubuntu1804

branches:
  only:
    - main

init:
  - echo "Performing initialization tasks..."
  - sudo apt-get update
  - sudo apt-get install -y curl


build_script:
  - echo "Checking current directory..."
  - pwd
  - echo "Listing contents of the directory..."
  - ls -la
  - echo "Changing to client directory..."
  - cd client || exit 1
  - echo "Current directory:"
  - pwd
  - echo "Listing contents of the directory..."
  - ls -la
  - echo "Installing dependencies..."
  - npm install
  - echo "Removing old dist directory..."
  - rm -rf dist/
  - echo "Building the project..."
  - npm run build


deploy_script:
  - cd client  
  - echo "Deploying to GitHub Pages..."
  - git config user.name "AppVeyor"  
  - git config user.email "ci@appveyor.com"  
  - git config credential.helper "store --file=$HOME/.git-credentials"  
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"  
  - git checkout gh-pages || git checkout --orphan gh-pages
  - rm -rf *
  - cp -r dist/* .
  - git add .
  - git commit -m "Deploy to GitHub Pages"
  - git push origin gh-pages
